
            MMMMMM     ,MMMMMN                                                  
             MMMMM8     $MMMMM?                                                 
              MMMMMM     ~MMMMMO                                                
               MMMMMM     ~MMMMMO                                               
                MMMMM$     8MMMMM~                                         
        DMD     ,MMMMMN     ?MMMMM                                 
      +MMMMMM    ,MMMMMN     ?MMMMM7                 
      NMMMMMM     7MMMMM+     NMMMMM,  
       MMMMM+      ~MMMMMZ     $MMMM8 
                    ~MMMM       =MMM=

Pyramid Linux, brought to you by .\\etrix Communication LLC

You have 10 seconds to choose an option from the menu below
otherwise after 10 seconds has elasped option 1 will 
automatically start. You may also pass kernel parameters at 
this time if desired.

Choose from one of the following:

1. Start the automated Pyramid Linux install process via dd image file

2. Start the automated Pyramid Linux install process via fdisk and tarball

3. Boot the Pyramid Linux kernel with a shell prompt

4. Boot the Pebble Linux install process 

5. Boot the Pebble Linux kernel with a shell

