#!/bin/sh
# Start/stop the cron daemon.

test -f /sbin/cron || exit 0

#LSBNAMES='-l'  # Uncomment for LSB name support in /etc/cron.d/

. /lib/lsb/init-functions

case "$1" in
start)	log_begin_msg "Starting periodic command scheduler..."
        start-stop-daemon --start --quiet --pidfile /var/run/crond.pid --name cron --startas /sbin/cron -- $LSBNAMES
        log_end_msg $?
	;;
stop)	log_begin_msg "Stopping periodic command scheduler..."
        start-stop-daemon --stop --quiet --pidfile /var/run/crond.pid --name cron
        log_end_msg $?
        ;;
restart) log_begin_msg "Restarting periodic command scheduler..."
        start-stop-daemon --stop --retry 5 --quiet --pidfile /var/run/crond.pid --name cron
        start-stop-daemon --start --quiet --pidfile /var/run/crond.pid --name cron --startas /sbin/cron -- $LSBNAMES
        log_end_msg $?
        ;;
reload|force-reload) log_begin_msg "Reloading configuration files for periodic command scheduler..."
	# cron reloads automatically
        log_end_msg 0
        ;;
*)	log_success_msg "Usage: /etc/init.d/cron start|stop|restart|reload|force-reload"
        exit 1 
        ;;
esac
exit 0
