#!/bin/sh

RRDTOOL="/bin/rrdtool"
DATADIR="/var/tmp/rrd/rrd_database"
WUSERS="/sbin/wusers"

[ -z "$1" ] && echo "Usage: $0 [interface]" && exit

INTERFACE=$1

OUT=`$WUSERS $INTERFACE`

$RRDTOOL update $DATADIR/$INTERFACE-nusers.rrd N:$OUT
