#!/bin/sh

RRDTOOL=/usr/bin/rrdtool
DATADIR="/var/tmp/rrd/rrd_database"
NETCAT="/usr/bin/nc"

[ -z "$3" ] && echo "Usage: $0 [host] [baseport] [variables...]" && exit

HOSTNAME=$1
BASEPORT=$2
shift
shift

PORT=$BASEPORT
for i in $*; do
  OUT=`$NETCAT $HOSTNAME $PORT`
  PORT=$((PORT + 1))

  $RRDTOOL update $DATADIR/${HOSTNAME}_$i.rrd N:$OUT
done
