#!/bin/sh

RRDTOOL=/usr/bin/rrdtool
DATADIR="/var/tmp/rrd/rrd_database"
NETCAT="/usr/bin/nc"

[ -z "$3" ] && echo "Usage: $0 [host] [baseport] [variables...]" && exit

HOSTNAME=$1
BASEPORT=$2
shift
shift

PORT=$BASEPORT
for i in $*; do
  OUT=`$NETCAT $HOSTNAME $PORT`
  #
  # OUT should look something like this:
  # 
  # -54 dBm -100 dBm
  #
  SIGNAL=${OUT/ */}
  NOISE=${OUT/* dBm /}
  NOISE=${NOISE/ dBm/}

  #
  # Remove the - to keep rrd happy 
  #
  SIGNAL=${SIGNAL/-/}
  NOISE=${NOISE/-/}
  
  PORT=$((PORT + 1))
  $RRDTOOL update $DATADIR/${HOSTNAME}_${i}_radio.rrd N:$SIGNAL:$NOISE
done
